@JWT =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMzY0N2ExZC1iMzE2LTQ2MTAtOGRlZC05NWUyODY5MzdiZjAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTM4Mjc3NDksImV4cCI6MTc1NDQzMjU0OX0.9l7Yfe3A0HDXp13ueo5wEsnuh2oYOWskqcJ2VhXJSYs

### Create New Location (ADMIN only)
POST http://localhost:3000/locations
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "name": "Tharaka Nithi"
}


### Get All Locations (Public)
GET http://localhost:3000/locations
